import '../../../core/database/database.dart';

/// Service for generating export content at different granularities
class ExportGenerator {
  static const Map<String, String> _sectionNames = {
    'info': 'Project Info',
    'research': 'Research & Stack',
    'architecture': 'Technical Architecture',
    'features': 'Feature Breakdown',
    'labor': 'Division of Labor',
  };

  static const Map<String, List<String>> _sectionFields = {
    'info': ['Project Name', 'One-Liner', 'Target Users', 'Core Value Prop', 'Key Differentiators'],
    'research': ['Tech Stack', 'Dependencies', 'Best Practices', 'Common Pitfalls', 'Security'],
    'architecture': ['System Overview', 'Data Models', 'API Contracts', 'Auth Strategy', 'Deployment', 'Scalability'],
    'features': ['MVP Features', 'V1 Features', 'Future Enhancements', 'Time Estimates'],
    'labor': ['Work Packages', 'Phase Timeline', 'Dependencies', 'Critical Path'],
  };

  /// Generate README for a single field
  static String generateFieldReadme({
    required String projectName,
    required String sectionType,
    required String fieldName,
    required String fieldContent,
  }) {
    final buffer = StringBuffer();
    
    buffer.writeln('# $fieldName');
    buffer.writeln('');
    buffer.writeln('> Part of: ${_sectionNames[sectionType] ?? sectionType}');
    buffer.writeln('> Project: $projectName');
    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('');
    buffer.writeln(fieldContent.trim());
    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('');
    buffer.writeln('*Generated by Pathway Project Planner*');
    
    return buffer.toString();
  }

  /// Generate README for an entire section
  static String generateSectionReadme({
    required String projectName,
    required String sectionType,
    required String sectionContent,
  }) {
    final buffer = StringBuffer();
    final sectionName = _sectionNames[sectionType] ?? sectionType;
    
    buffer.writeln('# $sectionName');
    buffer.writeln('');
    buffer.writeln('> Project: $projectName');
    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('');
    buffer.writeln(sectionContent.trim());
    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('');
    buffer.writeln('*Generated by Pathway Project Planner*');
    
    return buffer.toString();
  }

  /// Generate combined README for multiple sections
  static String generateCombinedReadme({
    required String projectName,
    required List<ProjectSection> sections,
    required Map<String, bool> selectedSections,
  }) {
    final buffer = StringBuffer();
    
    buffer.writeln('# $projectName - Documentation');
    buffer.writeln('');
    buffer.writeln('> Comprehensive project documentation generated by Pathway');
    buffer.writeln('');
    buffer.writeln('## Table of Contents');
    buffer.writeln('');
    
    // Generate TOC
    for (var entry in selectedSections.entries) {
      if (!entry.value) continue;
      final sectionName = _sectionNames[entry.key] ?? entry.key;
      buffer.writeln('- [$sectionName](#${_slugify(sectionName)})');
    }
    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('');
    
    // Generate sections
    for (var entry in selectedSections.entries) {
      if (!entry.value) continue;
      
      final section = sections.where((s) => s.sectionType == entry.key).firstOrNull;
      if (section == null) continue;
      
      final sectionName = _sectionNames[entry.key] ?? entry.key;
      buffer.writeln('## $sectionName');
      buffer.writeln('');
      buffer.writeln(section.content.trim());
      buffer.writeln('');
      buffer.writeln('---');
      buffer.writeln('');
    }
    
    buffer.writeln('*Generated by Pathway Project Planner on ${DateTime.now().toString().split('.')[0]}*');
    
    return buffer.toString();
  }

  /// Parse section content into fields
  static Map<String, String> parseFieldsFromContent(String sectionType, String content) {
    final fields = <String, String>{};
    final expectedFields = _sectionFields[sectionType] ?? [];
    
    if (expectedFields.isEmpty) return {'Content': content};
    
    final lines = content.split('\n');
    String? currentField;
    final currentContent = StringBuffer();
    
    for (var line in lines) {
      final trimmed = line.trim();
      
      // Check if line is a field header
      bool isFieldHeader = false;
      for (var field in expectedFields) {
        if (trimmed.toLowerCase() == field.toLowerCase() ||
            trimmed.toLowerCase() == '**${field.toLowerCase()}**' ||
            trimmed.toLowerCase() == '## ${field.toLowerCase()}' ||
            trimmed.toLowerCase() == '### ${field.toLowerCase()}') {
          isFieldHeader = true;
          
          // Save previous field
          if (currentField != null) {
            fields[currentField] = currentContent.toString().trim();
            currentContent.clear();
          }
          
          currentField = field;
          break;
        }
      }
      
      if (!isFieldHeader && currentField != null) {
        currentContent.writeln(line);
      }
    }
    
    // Save last field
    if (currentField != null) {
      fields[currentField] = currentContent.toString().trim();
    }
    
    return fields;
  }

  static String _slugify(String text) {
    return text.toLowerCase()
        .replaceAll(RegExp(r'[^\w\s-]'), '')
        .replaceAll(RegExp(r'[\s_]+'), '-')
        .replaceAll(RegExp(r'-+'), '-')
        .trim();
  }
}
